**TO - DO - Task**

In [1]:
# Task 1

def perform_unit_conversion(mode, input_value):
    """
    Transforms a numeric value from one unit of measurement to another.

    Parameters:
    mode (int): The conversion mode chosen by the user.
        1 - Meters to Feet
        2 - Feet to Meters
        3 - Kilograms to Pounds
        4 - Pounds to Kilograms
        5 - Liters to Gallons
        6 - Gallons to Liters
    input_value (float): The numeric quantity to be converted.

    Returns:
    float: The resulting converted quantity.
    """

    if mode == 1:
        return input_value * 3.28084  # meters to feet
    elif mode == 2:
        return input_value / 3.28084  # feet to meters
    elif mode == 3:
        return input_value * 2.20462  # kg to pounds
    elif mode == 4:
        return input_value / 2.20462  # pounds to kg
    elif mode == 5:
        return input_value * 0.264172  # liters to gallons
    elif mode == 6:
        return input_value / 0.264172  # gallons to liters
    else:
        return None


def run_converter():
    print("==== Unit Converter ====")
    print("Select Conversion Type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        selected_option = int(input("Enter your choice (1-6): "))

        if selected_option < 1 or selected_option > 6:
            print("Error: Invalid conversion type selected.")
            return

        user_value = float(input("Enter the value to convert: "))

        converted = perform_unit_conversion(selected_option, user_value)

        if converted is not None:
            print(f"Converted value: {converted:.4f}")
        else:
            print("Error: Conversion could not be performed.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


if __name__ == "__main__":
    run_converter()

==== Unit Converter ====
Select Conversion Type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 4
Enter the value to convert: 2
Converted value: 0.9072


In [2]:
def compute_total(data):
    """
    Computes the total sum of all values in the data list.

    Parameters:
    data (list of float): The collection of numeric values.

    Returns:
    float: The total sum of the values.
    """
    return sum(data)


def compute_mean(data):
    """
    Computes the arithmetic mean of all values in the data list.

    Parameters:
    data (list of float): The collection of numeric values.

    Returns:
    float: The mean of the values.
    """
    return sum(data) / len(data)


def get_largest(data):
    """
    Retrieves the largest value from the data list.

    Parameters:
    data (list of float): The collection of numeric values.

    Returns:
    float: The highest number in the list.
    """
    return max(data)


def get_smallest(data):
    """
    Retrieves the smallest value from the data list.

    Parameters:
    data (list of float): The collection of numeric values.

    Returns:
    float: The lowest number in the list.
    """
    return min(data)


def run_stats_menu():
    print("==== Mathematical Operations on a List ====")
    print("Select Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        selected_option = int(input("Enter your choice (1-4): "))

        if selected_option < 1 or selected_option > 4:
            print("Error: Invalid operation selected.")
            return

        raw_input = input("Enter numbers separated by spaces: ")

        # Convert input string to list of floats
        data = list(map(float, raw_input.split()))

        if len(data) == 0:
            print("Error: The list cannot be empty.")
            return

        if selected_option == 1:
            output = compute_total(data)
            print(f"Sum: {output}")
        elif selected_option == 2:
            output = compute_mean(data)
            print(f"Average: {output}")
        elif selected_option == 3:
            output = get_largest(data)
            print(f"Maximum: {output}")
        elif selected_option == 4:
            output = get_smallest(data)
            print(f"Minimum: {output}")

    except ValueError:
        print("Error: Please enter valid numeric values.")


if __name__ == "__main__":
    run_stats_menu()

==== Mathematical Operations on a List ====
Select Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 2
Enter numbers separated by spaces: 2
Average: 2.0


**Exercise on List Manipulation**

In [3]:
# 1. Pick Every Alternate Element:

def pick_alternate_elements(seq):
    return seq[::2]


# Example usage
sample_nums = [1, 2, 3, 4, 5, 6]
output = pick_alternate_elements(sample_nums)
print(output)


[1, 3, 5]


In [4]:
# 2. Extract a Range of Elements:

def extract_range(seq, begin, finish):
    return seq[begin:finish+1]


# Example usage
sample_nums = [10, 20, 30, 40, 50, 60]
output = extract_range(sample_nums, 1, 4)
print(output)

[20, 30, 40, 50]


In [5]:
# 3. Reverse a List Using Slicing:
def reverse_sequence(seq):
    return seq[::-1]


# Example usage
sample_nums = [10, 20, 30, 40, 50, 60]
output = reverse_sequence(sample_nums)
print(output)

[60, 50, 40, 30, 20, 10]


In [6]:
# 4. Strip the First and Last Elements:
def strip_endpoints(seq):
    return seq[1:-1]


# Example usage
sample_nums = [1, 2, 3, 4, 5]
output = strip_endpoints(sample_nums)
print(output)

[2, 3, 4]


In [7]:
# 5. Retrieve the Leading n Elements:
def get_leading_n(seq, count):
    return seq[:count]


# Example usage
sample_nums = [1, 2, 3, 4, 5]
output = get_leading_n(sample_nums, 3)
print(output)

[1, 2, 3]


In [8]:
# 7. Retrieve the Trailing n Elements:
def get_trailing_n(seq, count):
    return seq[-count:]


# Example usage
sample_nums = [1, 2, 3, 4, 5]
output = get_trailing_n(sample_nums, 2)
print(output)

[4, 5]


**Exercise on Nested List:**

In [9]:
# 1. Collapse a Nested List into a Single Layer:

def collapse_nested(nested):
    collapsed = []
    for inner in nested:
        for val in inner:
            collapsed.append(val)
    return collapsed


# Example usage
grouped_nums = [[1, 2], [3, 4], [5]]
output = collapse_nested(grouped_nums)
print(output)

[1, 2, 3, 4, 5]


In [10]:
# 2. Retrieve Element by Index Path in a Nested List:

def fetch_by_path(nested, path):
    target = nested
    for idx in path:
        target = target[idx]
    return target

# Example usage:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index_path = [1, 2]

output = fetch_by_path(matrix, index_path)
print(output)

6


In [11]:
# 3. Compute the Total of All Values in a Nested List:

def total_nested(nested):
    running_total = 0
    for entry in nested:
        if isinstance(entry, list):
            running_total += total_nested(entry)  # Recursively accumulate nested list values
        else:
            running_total += entry
    return running_total

# Example usage:
mixed_nested = [[1, 2], [3, [4, 5]], 6]
print(total_nested(mixed_nested))  # Output: 21

21


In [12]:
# 4. Delete a Target Value from a Nested List:

def delete_target(nested, target):
    filtered = []
    for entry in nested:
        if isinstance(entry, list):
            filtered.append(delete_target(entry, target))
        elif entry != target:
            filtered.append(entry)
    return filtered

# Example usage:
grouped = [[1, 2], [3, 2], [4, 5]]
target_val = 2
print(delete_target(grouped, target_val))

[[1], [3], [4, 5]]


In [13]:
# 5. Locate the Peak Element in a Nested List:

def locate_peak(nested):
    peak = float('-inf')  # Begin with the lowest possible starting value
    for entry in nested:
        if isinstance(entry, list):
            peak = max(peak, locate_peak(entry))  # Recursively locate peak in sublist
        else:
            peak = max(peak, entry)  # Compare against current entry
    return peak

# Example usage:
mixed_nested = [[1, 2], [3, [4, 5]], 6]
print(locate_peak(mixed_nested))

6


In [14]:
# 6. Tally Occurrences of a Value in a Nested List:
def tally_occurrences(nested, target):
    tally = 0
    for entry in nested:
        if isinstance(entry, list):
            tally += tally_occurrences(entry, target)  # Recursively tally in sublist
        elif entry == target:
            tally += 1
    return tally

# Example usage:
grouped = [[1, 2], [2, 3], [2, 4]]
target_val = 2
print(tally_occurrences(grouped, target_val))

3


In [15]:
# 7. Recursively Flatten a Deeply Nested List:

def fully_flatten(nested):
    flat = []
    for entry in nested:
        if isinstance(entry, list):
            flat.extend(fully_flatten(entry))  # Recursively flatten all sublists
        else:
            flat.append(entry)
    return flat

# Example usage:
deep_nested = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(fully_flatten(deep_nested))


[1, 2, 3, 4, 5, 6, 7, 8]


In [16]:
# 8. Mean Value of All Elements in a Nested List:

def mean_of_nested(nested):
    def accumulate(nested):
        grand_total = 0
        item_count = 0
        for entry in nested:
            if isinstance(entry, list):
                sub_total, sub_count = accumulate(entry)
                grand_total += sub_total
                item_count += sub_count
            else:
                grand_total += entry
                item_count += 1
        return grand_total, item_count

    grand_total, item_count = accumulate(nested)
    return grand_total / item_count if item_count != 0 else 0

# Example usage:
grouped_nums = [[1, 2], [3, 4], [5, 6]]
print(mean_of_nested(grouped_nums))

3.5


# **To - Do - NumPy**

In [17]:
import numpy as np

In [18]:
# Problem - 1: Array Initialization:

# 1. Create an uninitialized array of shape 2x2
blank_grid = np.empty((2, 2))
print("1. Uninitialized 2x2 array:\n", blank_grid)

# 2. Create an all-ones array of shape 4x2
all_ones_grid = np.ones((4, 2))
print("\n2. All-ones 4x2 array:\n", all_ones_grid)

# 3. Create a constant-filled array of given shape and type
constant_grid = np.full((3, 3), 7, dtype=int)
print("\n3. Constant array (3x3 filled with 7):\n", constant_grid)

# 4. Create a zero array matching the shape and type of an existing array
zero_copy = np.zeros_like(constant_grid)
print("\n4. Zero-copy matching constant_grid:\n", zero_copy)

# 5. Create a ones array matching the shape and type of an existing array
ones_copy = np.ones_like(constant_grid)
print("\n5. Ones-copy matching constant_grid:\n", ones_copy)

# 6. Convert an existing Python list into a NumPy array
source_list = [1, 2, 3, 4]
converted_array = np.array(source_list)
print("\n6. NumPy array from list:\n", converted_array)

1. Uninitialized 2x2 array:
 [[2.56550052e-315 0.00000000e+000]
 [1.89812479e-052 2.54509931e-076]]

2. All-ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Constant array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zero-copy matching constant_grid:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones-copy matching constant_grid:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. NumPy array from list:
 [1 2 3 4]


In [19]:
# Problem - 2: Numerical Ranges and Array Indexing:

# 1. Build an array with values from 10 to 49
range_arr = np.arange(10, 50)
print("1.\n", range_arr)

# 2. Build a 3x3 matrix with values from 0 to 8
reshaped_arr = np.arange(0, 9).reshape(3, 3)
print("\n2.\n", reshaped_arr)

# 3. Build a 3x3 identity matrix
identity_mat = np.eye(3)
print("\n3.\n", identity_mat)

# 4. Build a random array of 30 elements and compute the mean
rand_arr = np.random.random(30)
avg_val = rand_arr.mean()
print("\n4.\nArray:\n", rand_arr)
print("Mean:", avg_val)

# 5. Build a 10x10 random array and find its min and max
rand_grid = np.random.random((10, 10))
print("\n5.\nMin:", rand_grid.min())
print("Max:", rand_grid.max())

# 6. Build a zero array of size 10 and set the 5th element to 1
base_arr = np.zeros(10)
base_arr[4] = 1   # Index 4 = 5th element
print("\n6.\n", base_arr)

# 7. Reverse the given array
original_arr = np.array([1, 2, 0, 0, 4, 0])
flipped_arr = original_arr[::-1]
print("\n7.\n", flipped_arr)

# 8. Build a 2D array with border of 1s and interior of 0s
bordered_grid = np.ones((5, 5))
bordered_grid[1:-1, 1:-1] = 0
print("\n8.\n", bordered_grid)

# 9. Build an 8x8 checkerboard pattern
chess_board = np.zeros((8, 8), dtype=int)
chess_board[1::2, ::2] = 1
chess_board[::2, 1::2] = 1
print("\n9.\n", chess_board)

1.
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3.
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4.
Array:
 [0.89489379 0.03449403 0.04372209 0.72699429 0.26856891 0.00142109
 0.66553341 0.02891894 0.82733978 0.76844518 0.33907699 0.5608378
 0.13034104 0.1826083  0.26178707 0.77313107 0.41505287 0.74836142
 0.05507385 0.26595888 0.90515666 0.32857287 0.28369292 0.45485122
 0.78673489 0.11418199 0.83831609 0.74346898 0.65326693 0.98801379]
Mean: 0.46962723781426546

5.
Min: 0.00043924058144451106
Max: 0.9975679689809137

6.
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7.
 [0 4 0 0 2 1]

8.
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9.
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
# Problem - 3: Element-wise and Matrix Array Operations:

# Given arrays
mat_p = np.array([[1, 2], [3, 5]])
mat_q = np.array([[5, 6], [7, 8]])

vec_a = np.array([9, 10])
vec_b = np.array([11, 12])

# 1. Add the two matrices (mat_p and mat_q)
sum_pq = mat_p + mat_q
print("1. Addition:\n", sum_pq)

# 2. Subtract the two matrices (mat_p and mat_q)
diff_pq = mat_p - mat_q
print("\n2. Subtraction:\n", diff_pq)

# 3. Scale the matrix by an integer (e.g., 3)
scaled_p = mat_p * 3
print("\n3. Multiply mat_p by 3:\n", scaled_p)

# 4. Element-wise square of each value
squared_p = mat_p ** 2
print("\n4. Square of mat_p:\n", squared_p)

# 5. Dot products
dot_ab = np.dot(vec_a, vec_b)
dot_pa = np.dot(mat_p, vec_a)
dot_pq = np.dot(mat_p, mat_q)

print("\n5. Dot Products:")
print("vec_a · vec_b =", dot_ab)
print("mat_p · vec_a =", dot_pa)
print("mat_p · mat_q =\n", dot_pq)

# 6. Concatenation
# Concatenate mat_p and mat_q along rows
row_concat = np.concatenate((mat_p, mat_q), axis=0)
print("\n6. Concatenate mat_p and mat_q along rows:\n", row_concat)

# Concatenate vec_a and vec_b along columns
col_concat = np.vstack((vec_a, vec_b)).T
print("\nConcatenate vec_a and vec_b along column:\n", col_concat)

# 7. Concatenate mat_p and vec_a
# This will raise an error because dimensions do not align
# np.concatenate((mat_p, vec_a))  # Uncommenting this line will raise an error


1. Addition:
 [[ 6  8]
 [10 13]]

2. Subtraction:
 [[-4 -4]
 [-4 -3]]

3. Multiply mat_p by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of mat_p:
 [[ 1  4]
 [ 9 25]]

5. Dot Products:
vec_a · vec_b = 219
mat_p · vec_a = [29 77]
mat_p · mat_q =
 [[19 22]
 [50 58]]

6. Concatenate mat_p and mat_q along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate vec_a and vec_b along column:
 [[ 9 11]
 [10 12]]


In [21]:
# Problem - 4: Matrix Operations:

# Given Matrices
M = np.array([[3, 4],
              [7, 8]])

N = np.array([[5, 3],
              [2, 1]])

# 1. Prove M.M−1 = I

M_inv = np.linalg.inv(M)       # Inverse of M
identity_check = np.matmul(M, M_inv)   # M * M⁻¹

print("M inverse:\n", M_inv)
print("\nM * M⁻¹:\n", identity_check)


M inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

M * M⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [22]:
# Demonstrate MN ≠ NM

product_MN = np.matmul(M, N)
product_NM = np.matmul(N, M)

print("MN:\n", product_MN)
print("\nNM:\n", product_NM)

MN:
 [[23 13]
 [51 29]]

NM:
 [[36 44]
 [13 16]]


In [23]:
# Verify (MN)^T = N^T M^T

lhs = (np.matmul(M, N)).T
rhs = np.matmul(N.T, M.T)

print("(MN)^T:\n", lhs)
print("\nN^T M^T:\n", rhs)

(MN)^T:
 [[23 51]
 [13 29]]

N^T M^T:
 [[23 51]
 [13 29]]


In [24]:
# Solve a System of Linear Equations Using Matrix Form

# Represent in Matrix Form CoeffMatrix * VarVector = ConstVector
CoeffMatrix = np.array([[2, -3, 1],
                        [1, -1, 2],
                        [3,  1, -1]])

ConstVector = np.array([-1, -3, 9])

CoeffMatrix_inv = np.linalg.inv(CoeffMatrix)
SolutionVec = np.matmul(CoeffMatrix_inv, ConstVector)

print("Solution using inverse method:\n", SolutionVec)
print(f"x = {SolutionVec[0]}\ny = {SolutionVec[1]}\nz = {SolutionVec[2]}")

Solution using inverse method:
 [ 2.  1. -2.]
x = 2.0
y = 1.0
z = -2.0


In [25]:
# Solve Directly Using np.linalg.solve()

DirectSolution = np.linalg.solve(CoeffMatrix, ConstVector)
print("Solution using np.linalg.solve():\n", DirectSolution)
print(f"x = {DirectSolution[0]}\ny = {DirectSolution[1]:.1f}\nz = {DirectSolution[2]}")

Solution using np.linalg.solve():
 [ 2.  1. -2.]
x = 2.0
y = 1.0
z = -2.0


**Experiment: How Fast is Numpy?**

Element-wise Addition

In [26]:
import time
import random

# Element-wise Addition using Python lists:

# Generate two lists each containing 1,000,000 random values
data_list_a = [random.random() for _ in range(1_000_000)]
data_list_b = [random.random() for _ in range(1_000_000)]

# Record time for element-wise addition
t_start = time.time()

sum_list = [a + b for a, b in zip(data_list_a, data_list_b)]

t_end = time.time()

print("Time taken using Python Lists:", t_end - t_start, "seconds")

Time taken using Python Lists: 0.12499260902404785 seconds


In [27]:
# Element-wise Addition using NumPy arrays:

# Generate two NumPy arrays each with 1,000,000 elements
np_arr_a = np.random.random(1_000_000)
np_arr_b = np.random.random(1_000_000)

# Record time for element-wise addition
t_start = time.time()

sum_np = np_arr_a + np_arr_b

t_end = time.time()

print("Time taken using NumPy Arrays:", t_end - t_start, "seconds")

Time taken using NumPy Arrays: 0.004983663558959961 seconds


Element-wise Multiplication

In [28]:
# Element-wise Multiplication using Python lists:

t_begin = time.time()

product_list = [a * b for a, b in zip(data_list_a, data_list_b)]

t_finish = time.time()

print("Element-wise Multiplication (List):", t_finish - t_begin, "seconds")

Element-wise Multiplication (List): 0.12602901458740234 seconds


In [29]:
# Element-wise Multiplication using NumPy arrays:
t_begin = time.time()

product_np = np_arr_a * np_arr_b

t_finish = time.time()

print("Element-wise Multiplication (NumPy):", t_finish - t_begin, "seconds")

Element-wise Multiplication (NumPy): 0.0091400146484375 seconds


Dot product

In [30]:
# Dot product using Python lists

t_begin = time.time()

inner_product_list = sum(a * b for a, b in zip(data_list_a, data_list_b))

t_finish = time.time()

print("Dot Product (List):", t_finish - t_begin, "seconds")

Dot Product (List): 0.13175702095031738 seconds


In [31]:
# Dot product using NumPy arrays
t_begin = time.time()

inner_product_np = np.dot(np_arr_a, np_arr_b)

t_finish = time.time()

print("Dot Product (NumPy):", t_finish - t_begin, "seconds")

Dot Product (NumPy): 0.00536036491394043 seconds


Matrix Multiplication

In [32]:
# Using Python lists
# Build two 1000x1000 matrices
dim = 1000
mat_X = [[random.random() for _ in range(dim)] for _ in range(dim)]
mat_Y = [[random.random() for _ in range(dim)] for _ in range(dim)]

t_begin = time.time()

# Matrix multiplication using nested loops
mat_result = [[0]*dim for _ in range(dim)]

for r in range(dim):
    for c in range(dim):
        for k in range(dim):
            mat_result[r][c] += mat_X[r][k] * mat_Y[k][c]

t_finish = time.time()

print("Matrix Multiplication (List):", t_finish - t_begin, "seconds")

Matrix Multiplication (List): 398.0643458366394 seconds


In [33]:
# Using NumPy arrays

np_mat_X = np.random.random((1000, 1000))
np_mat_Y = np.random.random((1000, 1000))

t_begin = time.time()

np_mat_result = np.dot(np_mat_X, np_mat_Y)

t_finish = time.time()

print("Matrix Multiplication (NumPy):", t_finish - t_begin, "seconds")

Matrix Multiplication (NumPy): 0.06807470321655273 seconds
